### ISSUE TITLE
Counting number of words and characters in textarea

### ISSUE THREAD

**Issue by CodeWithBishal** [vyomaaverse/ReLoud#16]
Hi, I would like to
Count the total number of words and characters in the textarea

**Comment by vyomaaverse** [comment]
Hi @CodeWithBishal , a similar issue is already open. Why not head on to that one and start working on it?
Here is the [link](https://github.com/vyomaaverse/ReLoud/issues/13) to the issue.
I'm editing this issue so that redundant issues could be avoided. 
You can still work on the third point in this one, would be a nice add on.

**Comment by CodeWithBishal** [comment]
sure, for responsiveness I would like to work on #13 
for other issues please assign #16 to me

**Comment by vyomaaverse** [comment]
Sure, you are on it, assigning the issues

**Comment by vyomaaverse** [comment]
closed by #18
